<style>

  @keyframes slideIn {
    0% {
        transform: translateX(-50px);
        opacity: 0;
    }
    100% {
        transform: translateX(0);
        opacity: 1;
    }
}

.card {
    border: 1px solid #e0e0e0;
    border-radius: 5px;
    padding: 20px;
    margin: 10px;
    width: 300px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    background-color: #f9f9f9;
    font-family: Arial, sans-serif;
    transform: scale(1);
    transition: transform 0.3s ease;
    cursor: pointer;
    animation: slideIn 0.5s ease;
}

.card:hover {
    transform: scale(1.05);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}

.card img {
    max-width: 100%;
    height: auto;
    border-radius: 5px;
    transition: transform 0.3s ease;
}

.card:hover img {
    transform: scale(1.1);
}

.card h3 {
    font-size: 20px;
    margin-top: 10px;
    font-weight: bold;
    color: #333;
}

.card p {
    margin-top: 10px;
    font-size: 14px;
    line-height: 1.4;
    color: #666;
}



</style>

<div style="display:flex;">
	<?php foreach ($this->getBrands() as $brand) : ?>
    <div class="card">
        <a href="<?php echo $brand->url_key ?>">
            <img src="<?php echo Mage::getBaseUrl('media').'/'.$brand->image; ?>" alt="Brand 1">
        </a>
        <h3><?php echo $brand->name; ?></h3>
    </div>
	<?php endforeach; ?>
</div