<?php $brandId =  $this->getRequest()->getParam('brand_id');

$products = $this->getProductsByBrand();
// echo "<pre>";
// print_r($products); die(); 
$brand = Mage::getModel('brand/brand')->load($brandId);
?>


<style>
.container {
  position: relative;
  width: 100%;
  height: 400px;
  overflow: hidden;
}

.banner {
  position: relative;
  width: 100%;
  height: 100%;
}

.banner-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.banner-text {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
  color: #fff;
}


.card {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 18rem;
  margin: 10px;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  transition: all 0.3s ease;
}

.card:hover {
  transform: scale(1.05);
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.card-image {
  width: 100%;
  height: 200px;
  object-fit: cover;
  border-radius: 5px;
}

.card-title {
  font-size: 18px;
  margin: 10px 0;
}

.card p {
  margin-bottom: 10px;
}

.card b {
  font-weight: bold;
}

.btn-primary {
  display: inline-block;
  padding: 8px 16px;
  margin-top: 10px;
  background-color: #007bff;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
  transition: all 0.3s ease;
}

.btn-primary:hover {
  background-color: #0056b3;
}
</style>

<div class="container">
  <div class="banner">
    <img class="banner-image" src="<?php echo Mage::getBaseUrl('media').$brand->banner_image ?>" alt="Banner Image">
  </div>
</div>

<div style="display: flex;">
  <?php foreach ($products as $key => $value): ?>
    <div class="card m-1">
      <img class="card-img-top card-image" src="<?php echo Mage::getBaseUrl('media').'catalog/product/' .$value->getImage() ?> " alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><?php echo $value->name ?></h5>
        <p class=""><?php echo $value->getShortDescription() ?></p>
        <p class=""><b>$ <?php echo $value->getPrice() ?></b></p>
        <?php echo $value->getUrlKey(); ?>
        <a href="<?php echo $this->getProductUrl($value); ?>" class="btn btn-primary">Order Now</a>
      </div>
    </div>
  <?php endforeach ?>
</div>
